### ISSUE TITLE
Provide audio/video codec information 

### ISSUE THREAD

**Issue by jbaconbits** [plexinc-plugins/GiantBomb.bundle#15]
It looks like the channel does not provide codec info, causing some clients to do an unnecessary transcode on files that should otherwise directplay.

Noted here by a Plex dev.
https://forums.plex.tv/discussion/comment/1047807/#Comment_1047807

**Comment by sander1** [comment]
Not sure why some clients ask for a transcode, because both the URL Service included in the Services bundle and the one included in the channel bundle provide audio and video codec information:

https://github.com/plexinc-plugins/GiantBomb.bundle/blob/master/Contents/Services/URL/GiantBomb/ServiceCode.pys#L3-L7

https://github.com/plexinc-plugins/Services.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.giantbomb/URL/GiantBomb/ServiceCode.pys#L3-L7

XML output from Plex Media Server contains this as well: http://pastebin.com/c9fUbvMe

**Comment by jbaconbits** [comment]
https://forums.plex.tv/discussion/comment/1049574/#Comment_1049574

"The streams in the part(s) are missing the codec.

 <Stream index="0" selected="1" streamType="1" height="720" width="1280" bitrate="3744" id="1"/>
 <Stream index="1" selected="1" streamType="2" bitrate="256" id="2"/>
"

**Comment by sander1** [comment]
Fixed with https://github.com/plexinc-plugins/GiantBomb.bundle/commit/cdfc5d328d161cd7fed69d695ac47362ef045c8d
